import { test, expect, type Page, type Route } from '@playwright/test';
import { mockOperatorDetection, mockNamespaces, mockK8sResourceList } from '../support/mock-api';
import { checkErrors } from '../support/index';
import mockCertificates from '../fixtures/mock-certificates.json';
import mockIssuers from '../fixtures/mock-issuers.json';
import mockBundles from '../fixtures/mock-bundles.json';

/**
 * E2E tests for the "Related resources" relationship graph on ResourceInspect.
 * PR #124: feat: related resources graph on ResourceInspect
 * Ticket: none (standalone /opsx-e2e run, no prior Jira ticket)
 *
 * Framework note: generated against Playwright conventions used throughout
 * `integration-tests/tests/`, in place of the schema's default Ginkgo/envtest
 * template (this repo is a console plugin, not a Go operator).
 *
 * Covers: E2E-001, E2E-002, E2E-004, E2E-005, E2E-006, NEG-001, MQE-001 —
 * all verified passing against a real cluster + local console (see
 * openspec/changes/smc-inspect-graph/e2e/e2e-evaluation-report.md).
 *
 * Removed at user request after evaluation: E2E-003 (non-unique locator —
 * feature confirmed working, test needs exact-match fix), E2E-007 (blocked
 * by a pre-existing double-slash bug in mock-api.ts's namespaced-list
 * pattern, unrelated to this PR), NEG-002/NEG-003 (wrong assumption that
 * lookup failures show a panel-level Alert — the resolver actually degrades
 * per-node with "Not found"/"Insufficient permissions" badges). REG-001 is
 * a re-run of the existing inspect-pane.spec.ts, not new code — see the
 * evaluation report for full traceability against test-plan.md.
 *
 * Generated by OpenSpec /opsx-e2e
 */

// ─── Local helper: single-resource GET mock ───
// `ResourceInspect.tsx` watches a single resource via `useK8sWatchResource({ isList: false })`,
// which resolves to a per-name GET, not the list endpoint `mockK8sResourceList` already covers.
// No such helper exists yet in `integration-tests/support/mock-api.ts` — added here as a
// self-contained addition; consider upstreaming to `mock-api.ts` if reused by future inspect tests.
async function mockK8sResourceGet(
  page: Page,
  apiGroup: string,
  version: string,
  resource: string,
  namespace: string | undefined,
  name: string,
  item: unknown,
): Promise<void> {
  const pattern = namespace
    ? `**/api/kubernetes/apis/${apiGroup}/${version}/namespaces/${namespace}/${resource}/${name}`
    : `**/api/kubernetes/apis/${apiGroup}/${version}/${resource}/${name}`;
  await page.route(pattern, (route: Route) =>
    route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(item) }),
  );
}

const CERT_NAMESPACE = 'cert-manager-operator';
const CERT_NAME = 'selfsigned-ca-2';
const ISSUER_NAME = 'selfsigned-issuer';
const CERT_INSPECT_URL = `/secrets-management/inspect/certificates/${CERT_NAMESPACE}/${CERT_NAME}`;

const BUNDLE_NAME = 'organization-ca-bundle';
const BUNDLE_INSPECT_URL = `/secrets-management/inspect/bundles/${BUNDLE_NAME}`;

const cert = mockCertificates.find((c) => c.metadata.name === CERT_NAME);
const bundle = mockBundles.find((b) => b.metadata.name === BUNDLE_NAME);

test.describe('Related resources graph on ResourceInspect', () => {
  test.afterEach(async ({ page }) => {
    await checkErrors(page);
  });

  // ─── E2E-001 / MQE-001: Panel renders, is lazy, and expands ───

  test.describe('Panel rendering and lazy fetch', () => {
    test.beforeEach(async ({ page }) => {
      await mockOperatorDetection(page, { certManager: true });
      await mockNamespaces(page, [CERT_NAMESPACE]);
      await mockK8sResourceGet(page, 'cert-manager.io', 'v1', 'certificates', CERT_NAMESPACE, CERT_NAME, cert);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'issuers', []);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'clusterissuers', mockIssuers);
    });

    test('E2E-001: panel is collapsed by default and expands on click', async ({ page }) => {
      let relationshipFetchCount = 0;
      await page.route('**/api/kubernetes/apis/cert-manager.io/v1/clusterissuers/*', async (route) => {
        relationshipFetchCount += 1;
        await route.continue();
      });

      await page.goto(CERT_INSPECT_URL);
      await expect(page.getByText('Certificate:', { exact: false })).toBeVisible({ timeout: 60000 });

      // `data-test="relationship-graph-panel-toggle"` is on the whole PatternFly
      // ExpandableSection wrapper (toggle + body), not the inner clickable <button>
      // it renders. Scope to the button role so `.click()` actually fires `onToggle`.
      const toggleSection = page.locator('[data-test="relationship-graph-panel-toggle"]');
      const toggleButton = toggleSection.getByRole('button', { name: 'Related resources' });
      await expect(toggleButton).toBeVisible();

      // PR-REQ-001: no fetch before first expand
      expect(relationshipFetchCount).toBe(0);

      await toggleButton.click();

      // Graph should render with at least the Certificate + its ClusterIssuer.
      const summary = page.getByText(/resources, .* relationships/);
      await expect(summary).toBeVisible({ timeout: 15000 });
    });

    test('MQE-001: no relationship API calls fire before the panel is expanded', async ({ page }) => {
      let relationshipFetchCount = 0;
      await page.route('**/api/kubernetes/apis/cert-manager.io/v1/clusterissuers/*', async (route) => {
        relationshipFetchCount += 1;
        await route.continue();
      });

      await page.goto(CERT_INSPECT_URL);
      await expect(page.getByText('Certificate:', { exact: false })).toBeVisible({ timeout: 60000 });

      // Observe network for a short window with the panel still collapsed.
      await page.waitForTimeout(2000);
      expect(relationshipFetchCount).toBe(0);
    });
  });

  // ─── E2E-002: Certificate → Issuer relationship ───

  test.describe('Certificate to Issuer relationship', () => {
    test('E2E-002: graph shows the referenced ClusterIssuer node and an edge to it', async ({ page }) => {
      await mockOperatorDetection(page, { certManager: true });
      await mockNamespaces(page, [CERT_NAMESPACE]);
      await mockK8sResourceGet(page, 'cert-manager.io', 'v1', 'certificates', CERT_NAMESPACE, CERT_NAME, cert);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'clusterissuers', mockIssuers);

      await page.goto(CERT_INSPECT_URL);
      await expect(page.getByText('Certificate:', { exact: false })).toBeVisible({ timeout: 60000 });

      await page
        .locator('[data-test="relationship-graph-panel-toggle"]')
        .getByRole('button', { name: 'Related resources' })
        .click();

      await expect(page.getByText(ISSUER_NAME)).toBeVisible({ timeout: 15000 });

      // At least Certificate + Issuer + one edge.
      await expect(page.getByText(/[2-9] resources, [1-9] relationship/)).toBeVisible();
    });
  });

  // ─── E2E-004: Node click navigates to the related resource's inspect page ───

  test.describe('Node navigation', () => {
    test('E2E-004: clicking the Issuer node navigates to its inspect page', async ({ page }) => {
      await mockOperatorDetection(page, { certManager: true });
      await mockNamespaces(page, [CERT_NAMESPACE]);
      await mockK8sResourceGet(page, 'cert-manager.io', 'v1', 'certificates', CERT_NAMESPACE, CERT_NAME, cert);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'clusterissuers', mockIssuers);
      await mockK8sResourceGet(page, 'cert-manager.io', 'v1', 'clusterissuers', undefined, ISSUER_NAME, mockIssuers[0]);

      await page.goto(CERT_INSPECT_URL);
      await expect(page.getByText('Certificate:', { exact: false })).toBeVisible({ timeout: 60000 });
      await page
        .locator('[data-test="relationship-graph-panel-toggle"]')
        .getByRole('button', { name: 'Related resources' })
        .click();

      const issuerNode = page.getByText(ISSUER_NAME);
      await expect(issuerNode).toBeVisible({ timeout: 15000 });
      await issuerNode.click();

      await expect(page).toHaveURL(new RegExp(`/inspect/clusterissuers/.*${ISSUER_NAME}`), { timeout: 15000 });
      await expect(page.getByText('ClusterIssuer:', { exact: false })).toBeVisible({ timeout: 30000 });
    });
  });

  // ─── E2E-005: Refresh re-fetches relationship data ───

  test.describe('Refresh action', () => {
    test('E2E-005: clicking Refresh disables the button during re-fetch and re-renders the graph', async ({ page }) => {
      await mockOperatorDetection(page, { certManager: true });
      await mockNamespaces(page, [CERT_NAMESPACE]);
      await mockK8sResourceGet(page, 'cert-manager.io', 'v1', 'certificates', CERT_NAMESPACE, CERT_NAME, cert);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'clusterissuers', mockIssuers);

      await page.goto(CERT_INSPECT_URL);
      await expect(page.getByText('Certificate:', { exact: false })).toBeVisible({ timeout: 60000 });
      await page
        .locator('[data-test="relationship-graph-panel-toggle"]')
        .getByRole('button', { name: 'Related resources' })
        .click();
      await expect(page.getByText(ISSUER_NAME)).toBeVisible({ timeout: 15000 });

      const refreshButton = page.locator('[data-test="relationship-graph-refresh"]');
      await expect(refreshButton).toBeEnabled();
      await refreshButton.click();

      // Refresh re-fetches; graph re-renders with the same (unchanged, since we didn't alter the mock) data.
      await expect(page.getByText(ISSUER_NAME)).toBeVisible({ timeout: 15000 });
    });
  });

  // ─── E2E-006: Bundle → source relationships ───

  test.describe('Bundle source relationships', () => {
    test('E2E-006: graph shows the source Secret referenced by the Bundle', async ({ page }) => {
      await mockOperatorDetection(page, { trustManager: true });
      await mockNamespaces(page, ['default']);
      await mockK8sResourceGet(page, 'trust.cert-manager.io', 'v1alpha1', 'bundles', undefined, BUNDLE_NAME, bundle);

      await page.goto(BUNDLE_INSPECT_URL);
      await expect(page.getByText('Bundle:', { exact: false })).toBeVisible({ timeout: 60000 });
      await page
        .locator('[data-test="relationship-graph-panel-toggle"]')
        .getByRole('button', { name: 'Related resources' })
        .click();

      // Source secret named in mock-bundles.json fixture (`my-custom-ca-secret`).
      await expect(page.getByText('my-custom-ca-secret')).toBeVisible({ timeout: 15000 });
    });
  });

  // ─── NEG-001: Empty state ───

  test.describe('Empty state', () => {
    test('NEG-001: shows empty state when the resource has no relationships', async ({ page }) => {
      const isolatedIssuer = { ...mockIssuers[0], metadata: { ...mockIssuers[0].metadata, name: 'isolated-issuer' } };

      await mockOperatorDetection(page, { certManager: true });
      await mockNamespaces(page, ['default']);
      await mockK8sResourceGet(
        page,
        'cert-manager.io',
        'v1',
        'clusterissuers',
        undefined,
        'isolated-issuer',
        isolatedIssuer,
      );
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'certificates', []);

      await page.goto('/secrets-management/inspect/clusterissuers/isolated-issuer');
      await expect(page.getByText('ClusterIssuer:', { exact: false })).toBeVisible({ timeout: 60000 });
      await page
        .locator('[data-test="relationship-graph-panel-toggle"]')
        .getByRole('button', { name: 'Related resources' })
        .click();

      await expect(page.getByText('No related resources were found for this resource.')).toBeVisible({
        timeout: 15000,
      });
    });
  });
});

// ─── REG-001: Regression — existing inspect-pane suite is unaffected ───
//
// Not duplicated here. Run the existing, unmodified suite as-is against this PR's build:
//   npx playwright test integration-tests/tests/inspect-pane.spec.ts
// All 5 existing tests (kebab-menu open, Metadata section, Specification/Status sections,
// sensitive-data toggle, back button) must continue to pass unchanged — confirms the new
// `RelationshipGraphPanel` GridItem in `ResourceInspect.tsx` does not disturb the existing
// card layout (PR-REQ-008).
