import { test, expect } from '@playwright/test';
import {
  mockOperatorDetection,
  mockNamespaces,
  mockK8sResourceList,
} from '../support/mock-api';
import mockBundles from '../fixtures/mock-bundles.json';

/**
 * E2E tests for trust-manager Bundle resources on the Secrets Management dashboard.
 * PR #111: feat: add trust-manager Bundle resources to dashboard
 * Ticket: SMC-58
 *
 * Generated by OpenSpec /opsx-e2e
 */

test.describe('Trust Manager Bundles - Pre-merge E2E Tests', () => {
  // ─── Journey 1: Trust Bundles Table Rendering ───

  test.describe('Journey 1: Trust Bundles Table Rendering', () => {
    test.beforeEach(async ({ page }) => {
      await mockOperatorDetection(page, { trustManager: true });
      await mockNamespaces(page, ['default']);
      await mockK8sResourceList(page, 'trust.cert-manager.io', 'v1alpha1', 'bundles', mockBundles);
    });

    test('renders Trust Bundles section with table, heading, badge, and correct columns', async ({ page }) => {
      await page.goto('/secrets-management');

      // Verify page loads
      await expect(page.getByRole('heading', { name: 'Secrets Management' })).toBeVisible({
        timeout: 30000,
      });

      // Verify Trust Bundles heading
      await expect(page.getByRole('heading', { name: 'Trust Bundles', level: 3 })).toBeVisible({
        timeout: 15000,
      });

      // Verify trust-manager badge
      await expect(page.getByText('trust-manager')).toBeVisible();

      // Verify table is visible
      const table = page.locator('[data-test="bundles-table"]');
      await expect(table).toBeVisible({ timeout: 15000 });

      // Verify column headers
      await expect(table.getByText('Name')).toBeVisible();
      await expect(table.getByText('Sources')).toBeVisible();
      await expect(table.getByText('Target')).toBeVisible();
      await expect(table.getByText('Namespace Scope')).toBeVisible();
      await expect(table.getByText('Default CA Version')).toBeVisible();
      await expect(table.getByText('Status')).toBeVisible();

      // Verify bundle data renders
      await expect(table.getByText('organization-ca-bundle')).toBeVisible();
      await expect(table.getByText('java-app-truststore')).toBeVisible();

      // Verify sources column format
      await expect(table.getByText('Default CAs, Secret: my-custom-ca-secret')).toBeVisible();

      // Verify target with additional formats
      await expect(table.getByText('ConfigMap[ca-bundle.crt], JKS, PKCS12')).toBeVisible();

      // Verify namespace scope column
      await expect(table.getByText('All namespaces').first()).toBeVisible();
      await expect(table.getByText('inject-trust=true')).toBeVisible();

      // Verify CA version displays
      await expect(table.getByText('2024.2.69_v8.0.401')).toBeVisible();
    });
  });

  // ─── Journey 2: Bundle Status Labels & Actions ───

  test.describe('Journey 2: Bundle Status Labels & Actions', () => {
    test.beforeEach(async ({ page }) => {
      await mockOperatorDetection(page, { trustManager: true });
      await mockNamespaces(page, ['default']);
      await mockK8sResourceList(page, 'trust.cert-manager.io', 'v1alpha1', 'bundles', mockBundles);
    });

    test('displays correct status labels and kebab menu actions', async ({ page }) => {
      await page.goto('/secrets-management');

      const table = page.locator('[data-test="bundles-table"]');
      await expect(table).toBeVisible({ timeout: 30000 });

      // Verify Synced status label (green success)
      const syncedLabels = table.locator('.pf-v6-c-label, .pf-v5-c-label').filter({ hasText: 'Synced' });
      await expect(syncedLabels.first()).toBeVisible();

      // Verify SyncFailed status label (red danger)
      await expect(table.getByText('SyncFailed')).toBeVisible();

      // Verify Unknown status label (yellow warning) for bundle with no conditions
      await expect(table.getByText('Unknown')).toBeVisible();

      // Verify kebab menu exists
      const kebabButtons = table.getByRole('button', { name: /kebab dropdown toggle/i });
      expect(await kebabButtons.count()).toBeGreaterThanOrEqual(1);

      // Click first kebab menu
      await kebabButtons.first().click();

      // Verify menu items
      await expect(page.getByRole('menuitem', { name: 'Inspect Bundle' })).toBeVisible();
      await expect(page.getByRole('menuitem', { name: 'Delete Bundle' })).toBeVisible();
    });
  });

  // ─── Journey 3: Operator Detection & Section Visibility ───

  test.describe('Journey 3: Operator Detection & Section Visibility', () => {
    test('shows Trust Bundles section when trust-manager CRD exists', async ({ page }) => {
      await mockOperatorDetection(page, { trustManager: true, certManager: true });
      await mockNamespaces(page, ['default']);
      await mockK8sResourceList(page, 'trust.cert-manager.io', 'v1alpha1', 'bundles', []);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'certificates', []);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'issuers', []);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'clusterissuers', []);

      await page.goto('/secrets-management');

      await expect(page.getByRole('heading', { name: 'Secrets Management' })).toBeVisible({
        timeout: 30000,
      });

      // Trust Bundles section should be visible
      await expect(page.getByRole('heading', { name: 'Trust Bundles', level: 3 })).toBeVisible({
        timeout: 15000,
      });
    });

    test('hides Trust Bundles section when trust-manager CRD does not exist', async ({ page }) => {
      // Only cert-manager installed, not trust-manager
      await mockOperatorDetection(page, { trustManager: false, certManager: true, externalSecrets: true });
      await mockNamespaces(page, ['default']);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'certificates', []);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'issuers', []);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'clusterissuers', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1', 'externalsecrets', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1', 'secretstores', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1', 'clustersecretstores', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1alpha1', 'pushsecrets', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1alpha1', 'clusterpushsecrets', []);

      await page.goto('/secrets-management');

      await expect(page.getByRole('heading', { name: 'Secrets Management' })).toBeVisible({
        timeout: 30000,
      });

      // Trust Bundles section should NOT be visible
      await expect(page.getByRole('heading', { name: 'Trust Bundles', level: 3 })).not.toBeVisible();

      // Other sections should still be visible
      await expect(page.getByRole('heading', { name: 'Certificates', level: 3 })).toBeVisible();
      await expect(page.getByRole('heading', { name: 'External Secrets', level: 3 })).toBeVisible();
    });
  });

  // ─── Journey 4: Filter Functionality ───

  test.describe('Journey 4: Filter Functionality', () => {
    test.beforeEach(async ({ page }) => {
      await mockOperatorDetection(page, {
        certManager: true,
        trustManager: true,
        externalSecrets: true,
        secretsStoreCSI: true,
      });
      await mockNamespaces(page, ['default', 'cert-manager-operator']);
      await mockK8sResourceList(page, 'trust.cert-manager.io', 'v1alpha1', 'bundles', mockBundles);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'certificates', []);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'issuers', []);
      await mockK8sResourceList(page, 'cert-manager.io', 'v1', 'clusterissuers', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1', 'externalsecrets', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1', 'secretstores', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1', 'clustersecretstores', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1alpha1', 'pushsecrets', []);
      await mockK8sResourceList(page, 'external-secrets.io', 'v1alpha1', 'clusterpushsecrets', []);
      await mockK8sResourceList(page, 'secrets-store.csi.x-k8s.io', 'v1', 'secretproviderclasses', []);
      await mockK8sResourceList(page, 'secrets-store.csi.x-k8s.io', 'v1', 'secretproviderclasspodstatuses', []);
    });

    test('filter dropdowns include trust-manager options and filtering works', async ({ page }) => {
      await page.goto('/secrets-management');

      await expect(page.getByRole('heading', { name: 'Secrets Management' })).toBeVisible({
        timeout: 30000,
      });

      // Verify all sections initially visible
      await expect(page.getByRole('heading', { name: 'Trust Bundles', level: 3 })).toBeVisible();
      await expect(page.getByRole('heading', { name: 'Certificates', level: 3 })).toBeVisible();

      // Click Operator filter dropdown
      await page.getByLabel('Operator').click();

      // Verify trust-manager option exists
      await expect(page.getByText('trust-manager').first()).toBeVisible();
      await expect(page.getByText('CA trust bundle distribution')).toBeVisible();

      // Close and click Resource Type filter
      await page.keyboard.press('Escape');
      await page.getByLabel('Resource Type').click();

      // Verify Bundles option exists
      await expect(page.getByRole('option', { name: /Bundles/i })).toBeVisible();

      // Close dropdown
      await page.keyboard.press('Escape');

      // Select trust-manager from Operator filter
      await page.getByLabel('Operator').click();
      await page.getByText('trust-manager').first().click();

      // Only Trust Bundles section should be visible
      await expect(page.getByRole('heading', { name: 'Trust Bundles', level: 3 })).toBeVisible();
      await expect(page.getByRole('heading', { name: 'Certificates', level: 3 })).not.toBeVisible();
      await expect(page.getByRole('heading', { name: 'External Secrets', level: 3 })).not.toBeVisible();
    });
  });

  // ─── Journey 5: Table Column Data Formatting ───

  test.describe('Journey 5: Table Column Data Formatting', () => {
    test.beforeEach(async ({ page }) => {
      await mockOperatorDetection(page, { trustManager: true });
      await mockNamespaces(page, ['default']);
      await mockK8sResourceList(page, 'trust.cert-manager.io', 'v1alpha1', 'bundles', mockBundles);
    });

    test('columns display correctly formatted data for various bundle configurations', async ({ page }) => {
      await page.goto('/secrets-management');

      const table = page.locator('[data-test="bundles-table"]');
      await expect(table).toBeVisible({ timeout: 30000 });

      // Sources column formatting

      // Bundle with useDefaultCAs + named secret
      await expect(table.getByText('Default CAs, Secret: my-custom-ca-secret')).toBeVisible();

      // Bundle with secret selector
      await expect(table.getByText('Secret (selector)')).toBeVisible();

      // Target column with additional formats (JKS, PKCS12)
      await expect(table.getByText('ConfigMap[ca-bundle.crt], JKS, PKCS12')).toBeVisible();

      // Target column without additional formats
      const simpleTargets = table.getByText('ConfigMap[ca-bundle.crt]');
      expect(await simpleTargets.count()).toBeGreaterThanOrEqual(1);

      // Namespace Scope column - "All namespaces" for bundles without selector
      const allNamespaces = table.getByText('All namespaces');
      expect(await allNamespaces.count()).toBeGreaterThanOrEqual(1);

      // Namespace Scope column - label selector format
      await expect(table.getByText('inject-trust=true')).toBeVisible();
    });
  });

  // ─── Journey 6: Empty State Handling ───

  test.describe('Journey 6: Empty State Handling', () => {
    test('displays empty state when no bundles exist', async ({ page }) => {
      await mockOperatorDetection(page, { trustManager: true });
      await mockNamespaces(page, ['default']);
      await mockK8sResourceList(page, 'trust.cert-manager.io', 'v1alpha1', 'bundles', []);

      await page.goto('/secrets-management');

      await expect(page.getByRole('heading', { name: 'Secrets Management' })).toBeVisible({
        timeout: 30000,
      });

      // Trust Bundles section should be visible
      await expect(page.getByRole('heading', { name: 'Trust Bundles', level: 3 })).toBeVisible();

      // Empty state title
      await expect(page.getByText('No trust bundles found')).toBeVisible();

      // Empty state body with cluster-scoped explanation
      await expect(page.getByText(/cluster-scoped resources/i)).toBeVisible();

      // No table data rows should be visible
      const table = page.locator('[data-test="bundles-table"]');
      await expect(table.locator('tbody tr')).toHaveCount(0);
    });
  });

  // ─── Journey 7: Error State Handling ───

  test.describe('Journey 7: Error State Handling', () => {
    test('displays error state when Bundle API fails', async ({ page }) => {
      await mockOperatorDetection(page, { trustManager: true });
      await mockNamespaces(page, ['default']);

      // Mock Bundle API to return 500 error
      await page.route('**/api/kubernetes/apis/trust.cert-manager.io/v1alpha1/bundles?*', (route) =>
        route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({
            kind: 'Status',
            apiVersion: 'v1',
            status: 'Failure',
            message: 'Internal server error: Failed to fetch bundles',
            code: 500,
          }),
        }),
      );

      await page.goto('/secrets-management');

      await expect(page.getByRole('heading', { name: 'Secrets Management' })).toBeVisible({
        timeout: 30000,
      });

      // Trust Bundles section should be visible (operator is installed)
      await expect(page.getByRole('heading', { name: 'Trust Bundles', level: 3 })).toBeVisible();

      // Error message should be displayed
      await expect(page.getByText(/Failed to fetch bundles|error|Error/i)).toBeVisible({
        timeout: 15000,
      });

      // Page should remain interactive - filter dropdowns should still work
      await expect(page.getByLabel('Operator')).toBeEnabled();
    });
  });
});
